### ISSUE TITLE
How to change the configure in yaml to configure to deploy as traditional war file?

### ISSUE THREAD

**Issue by bluekanasword** [khoubyari/spring-boot-rest-example#2]
What is the configuration in yaml to configure to deploy as traditional war file in tomcat server?
There is not much example in yaml.

**Comment by zk4** [comment]
there`s some errors in application.yml profile.
check this fork. 
[https://github.com/zk4/springboot-rest-swagger2-test-example](https://github.com/zk4/springboot-rest-swagger2-test-example)

remember changing the mysql URL configuration ,username,password.

**Comment by khoubyari** [comment]
please refer to this blog: http://programmergate.com/deploy-spring-boot-application-external-tomcat/
