### ISSUE TITLE
Getting 406 error when going to the GET hotels resource

### ISSUE THREAD

**Issue by cosbor11** [khoubyari/spring-boot-rest-example#3]
Step To Reproduce: 
1. Build project
2. Run `java - jar -Dspring.profiles.active=test target/spring-boot-example-0-1.0.war`
3. Go to `localhost:8090/example/v1/hotels?page=0&size=10`
   
   ISSUE: 406 error returned

**Comment by khoubyari** [comment]
Hi! 

Did you provide the following HTTP header when you made the call

```
Content-Type: application/json
```

**Comment by cosbor11** [comment]
Oh shoot! This  was 3 months ago so I don't remember for sure, I'm assuming that I was probably just doing a get request with the chrome.

**Comment by khoubyari** [comment]
OK Thanks for the response. Since it's the likely cause, I will close this.
