### ISSUE TITLE
Please add in README how to launch swagger

### ISSUE THREAD

**Issue by paulvi** [khoubyari/spring-boot-rest-example#4]
Please add in README how to launch used swagger version (to generate docs)

**Comment by zk4** [comment]
check this fork [https://github.com/zk4/springboot-rest-swagger2-test-example](https://github.com/zk4/springboot-rest-swagger2-test-example).   

integrated with swagger2. you can visit swagger-ui  through [http://127.0.0.1:8090/swagger-ui.html](http://127.0.0.1:8090/swagger-ui.html)

**Comment by paulvi** [comment]
谢谢 Thanks

**Comment by khoubyari** [comment]
Fixed.
