### ISSUE TITLE
unable to install breakpoint

### ISSUE THREAD

**Issue by downgoon** [khoubyari/spring-boot-rest-example#8]
problem description

* set a breakpoint on Line 37 in ``HotelController.java``

``` java
@RestController
@RequestMapping(value = "/example/v1/hotels")
@Api(value = "hotels", description = "Hotel API")
public class HotelController extends AbstractRestHandler {

    @Autowired
    private HotelService hotelService;

    @RequestMapping(value = "",
            method = RequestMethod.POST,
            consumes = {"application/json", "application/xml"},
            produces = {"application/json", "application/xml"})
    @ResponseStatus(HttpStatus.CREATED)
    @ApiOperation(value = "Create a hotel resource.", notes = "Returns the URL of the new resource in the Location header.")
    public void createHotel(@RequestBody Hotel hotel,
                                 HttpServletRequest request, HttpServletResponse response) {
    	Hotel createdHotel = this.hotelService.createHotel(hotel);  // breakpoint on Line 37
        response.setHeader("Location", request.getRequestURL().append("/").append(createdHotel.getId()).toString());
    }
```

Line 37 content is 
>Hotel createdHotel = this.hotelService.createHotel(hotel);

* Debug As -> Java Application on ``Application.java`` in Eclipse
* **WARNING** unable to install breakpoint due to missing line number attributes Modify complier options

![unable to install breakpoint](https://cloud.githubusercontent.com/assets/23731186/20744065/b028ab18-b714-11e6-8849-c4152b7f7313.png)

* I have modified complier options ``Add line number ...``

![enable Add line number option](https://cloud.githubusercontent.com/assets/23731186/20744166/2cc51698-b715-11e6-9cd5-255648b526b5.png)

* due to **springCGLIB** ? or other things ?

**Comment by downgoon** [comment]
line number found in HotelController.class but i am not sure about CGLIB inner class HotelController$EnhancerBySpringCGLIB$e006d72

``` java
javap -c target/spring-boot-rest-example-0.3.0/WEB-INF/classes/com/khoubyari/example/api/rest/HotelController.class
```

[bytecode of HotelController.class](https://github.com/khoubyari/spring-boot-rest-example/files/621285/bytecode.txt)

by the way, the method proposed at this post [just ignore the warning](http://stackoverflow.com/questions/8195091/i-cant-debug-using-breakpoints) has no effects on my case.

**Comment by martinlippert** [comment]
I analyzed this in detail and wrote up the details about it here: https://github.com/spring-projects/spring-ide/issues/78.

**Comment by khoubyari** [comment]
IDE issue. Closing

**Comment by N0stalgia** [comment]
I was wondering if you solved this problem ?

**Comment by ghchae** [comment]
Breakpoints > remove all breakPoint

**Comment by martinlippert** [comment]
@N0stalgia The solution to this is mentioned in https://github.com/spring-projects/spring-ide/issues/78. There is an option to ignore this in the preferences.
